CREATE DATABASE  `inventory` ;

CREATE TABLE  `inventory`.`PRODUCTS` (
`ID` INT NOT NULL ,
`NAME` VARCHAR( 244 ) NOT NULL ,
`PRICE` DOUBLE NOT NULL
) ENGINE = MYISAM ;

CREATE USER 'idan'@'localhost' IDENTIFIED BY  '***';

GRANT USAGE ON * . * TO  'idan'@'localhost' IDENTIFIED BY  '***' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

GRANT ALL PRIVILEGES ON  `inventory` . * TO  'idan'@'localhost';